# Generated by Django 3.1.10 on 2021-05-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210515_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Correct Answer'), (0, 'Wrong Answer')], default=0),
        ),
    ]
