# Generated by Django 3.1.10 on 2021-05-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-has_completed', 'last_submission', '-code', '-has_completed'), 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_submission',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
